title: Jiageng Liu
# author: 
email: bioliu@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  Jiageng Liu, UCLA student, AI ethusiast.

# twitter_username: 
zhihu_username: jiagengliu
github_username:  jiagengliu

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.html
 - blog.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
